
spring.application.name=urlshortenerserver

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortenerdb

spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.id.default_value=IDENTITY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.username=postgres
spring.datasource.password=123456

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0

# Health and Readiness Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoint.health.group.readiness.include=readinessState,db

# Database Connection Pooling
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.leak-detection-threshold=20000

# Structured Log
logging.structured.format.console=logstash

spring.datasource.hikari.statement-timeout=10000



# HTTP client timeout
server.tomcat.connection-timeout=5000


# JWT
app.jwt.secret=mySuperSecretKeyThatIsAtLeast32BytesLong123456!@#
app.jwt.expiration-minutes=60

codeLength = 5